version: '3'
services:
        service1:
                build: ./App1
                ports:
                        - 8080:8080
                container_name: app1
        service2:
                build: ./App2
                ports:
                        - 8081:8080
                container_name: app2
        service3:
                image: mustafa150/myreverseproxy
                ports:
                        - 80:80
                container_name: reverseproxy
